export const options = (t) => ({
    gender:[
        {value:"bride",label: t("Options.gender.male")},
        {value:"groom",label: t("Options.gender.female")}
    ],
    minAgeOptions : Array.from({ length: 42 }, (_, i) => ({
        value: (i + 18).toString(),
        label: (i + 18).toString(),
      })),
      maxAgeOptions : [
        ...Array.from({ length: 43 }, (_, i) => ({
          value: (i + 18).toString(),
          label: (i + 18).toString(),
        })),
        { value: "60+", label: "60+" }
      ],
      casteOptions:[
        { value: "suthar", label: t("Options.caste.suthar") },
      ],
      subCasteOptions : [
        { value: "aasdev", label: t("Options.subCaste.aasdev") },
        { value: "adichawal", label: t("Options.subCaste.adichawal") },
        { value: "aadhana", label: t("Options.subCaste.aadhana") },
        { value: "achu", label: t("Options.subCaste.achu") },
        { value: "alodia", label: t("Options.subCaste.alodia") },
        { value: "aniwal", label: t("Options.subCaste.aniwal") },
        { value: "ankphod", label: t("Options.subCaste.ankphod") },
        { value: "asdamya", label: t("Options.subCaste.asdamya") },
        { value: "baghmar", label: t("Options.subCaste.baghmar") },
        { value: "bada", label: t("Options.subCaste.bada") },
        { value: "bahia", label: t("Options.subCaste.bahia") },
        { value: "baldeva", label: t("Options.subCaste.baldeva") },
        { value: "bardawa", label: t("Options.subCaste.bardawa") },
        { value: "bhatia", label: t("Options.subCaste.bhatia") },
        { value: "bhadania", label: t("Options.subCaste.bhadania") },
        { value: "bhadresa_bhadrecha", label: t("Options.subCaste.bhadresa_bhadrecha") },
        { value: "bhachanecha", label: t("Options.subCaste.bhachanecha") },
        { value: "bhambhoria", label: t("Options.subCaste.bhambhoria") },
        { value: "bharan_baran", label: t("Options.subCaste.bharan_baran") },
        { value: "bhana", label: t("Options.subCaste.bhana") },
        { value: "bhundad", label: t("Options.subCaste.bhundad") },
        { value: "bhundecha", label: t("Options.subCaste.bhundecha") },
        { value: "brahmadikshit", label: t("Options.subCaste.brahmadikshit") },
        { value: "brahmkhatri", label: t("Options.subCaste.brahmkhatri") },
        { value: "bundal", label: t("Options.subCaste.bundal") },
        { value: "bundiwal", label: t("Options.subCaste.bundiwal") },
        { value: "buns", label: t("Options.subCaste.buns") },
        { value: "chadiya", label: t("Options.subCaste.chadiya") },
        { value: "chandak", label: t("Options.subCaste.chandak") },
        { value: "chatrecha", label: t("Options.subCaste.chatrecha") },
        { value: "chanvla_dayama", label: t("Options.subCaste.chanvla_dayama") },
        { value: "chanvlared", label: t("Options.subCaste.chanvlared") },
        { value: "chundha_sanjob", label: t("Options.subCaste.chundha_sanjob") },
        { value: "chuyal", label: t("Options.subCaste.chuyal") },
        { value: "chuyal_choyal", label: t("Options.subCaste.chuyal_choyal") },
        { value: "depal", label: t("Options.subCaste.depal") },
        { value: "devda", label: t("Options.subCaste.devda") },
        { value: "deerak", label: t("Options.subCaste.deerak") },
        { value: "dhamu", label: t("Options.subCaste.dhamu") },
        { value: "dhadhala", label: t("Options.subCaste.dhadhala") },
        { value: "dhanekha", label: t("Options.subCaste.dhanekha") },
        { value: "doyal", label: t("Options.subCaste.doyal") },
        { value: "dugeshwar", label: t("Options.subCaste.dugeshwar") },
        { value: "fahrod", label: t("Options.subCaste.fahrod") },
        { value: "ganddi", label: t("Options.subCaste.ganddi") },
        { value: "gaipal", label: t("Options.subCaste.gaipal") },
        { value: "gaud", label: t("Options.subCaste.gaud") },
        { value: "goyal", label: t("Options.subCaste.goyal") },
        { value: "jalania", label: t("Options.subCaste.jalania") },
        { value: "jalodhiya_sindhad_singhal", label: t("Options.subCaste.jalodhiya_sindhad_singhal") },
        { value: "jambhad", label: t("Options.subCaste.jambhad") },
        { value: "jodh", label: t("Options.subCaste.jodh") },
        { value: "jodhariya", label: t("Options.subCaste.jodhariya") },
        { value: "jhans", label: t("Options.subCaste.jhans") },
        { value: "jhamdiya", label: t("Options.subCaste.jhamdiya") },
        { value: "kavchela", label: t("Options.subCaste.kavchela") },
        { value: "kingshya", label: t("Options.subCaste.kingshya") },
        { value: "kinnar", label: t("Options.subCaste.kinnar") },
        { value: "kolar", label: t("Options.subCaste.kolar") },
        { value: "kulsariya", label: t("Options.subCaste.kulsariya") },
        { value: "kulriya", label: t("Options.subCaste.kulriya") },
        { value: "leekhad", label: t("Options.subCaste.leekhad") },
        { value: "lekhrao", label: t("Options.subCaste.lekhrao") },
        { value: "makad", label: t("Options.subCaste.makad") },
        { value: "makuwana", label: t("Options.subCaste.makuwana") },
        { value: "mandana", label: t("Options.subCaste.mandana") },
        { value: "manlagrao", label: t("Options.subCaste.manlagrao") },
        { value: "marotia", label: t("Options.subCaste.marotia") },
        { value: "mahil", label: t("Options.subCaste.mahil") },
        { value: "motiyar", label: t("Options.subCaste.motiyar") },
        { value: "nagal", label: t("Options.subCaste.nagal") },
        { value: "nathala", label: t("Options.subCaste.nathala") },
        { value: "netal", label: t("Options.subCaste.netal") },
        { value: "nibhad", label: t("Options.subCaste.nibhad") },
        { value: "nisaan", label: t("Options.subCaste.nisaan") },
        { value: "polaria", label: t("Options.subCaste.polaria") },
        { value: "pakhrod", label: t("Options.subCaste.pakhrod") },
        { value: "palecha", label: t("Options.subCaste.palecha") },
        { value: "pingal", label: t("Options.subCaste.pingal") },
        { value: "pramsaiya", label: t("Options.subCaste.pramsaiya") },
        { value: "raanan", label: t("Options.subCaste.raanan") },
        { value: "rajwan", label: t("Options.subCaste.rajwan") },
        { value: "roham", label: t("Options.subCaste.roham") },
        { value: "rope", label: t("Options.subCaste.rope") },
        { value: "sahul", label: t("Options.subCaste.sahul") },
        { value: "sambiya", label: t("Options.subCaste.sambiya") },
        { value: "sanloon", label: t("Options.subCaste.sanloon") },
        { value: "seelang", label: t("Options.subCaste.seelang") },
        { value: "sen", label: t("Options.subCaste.sen") },
        { value: "siha", label: t("Options.subCaste.siha") },
        { value: "sokha", label: t("Options.subCaste.sokha") },
        { value: "suvkam", label: t("Options.subCaste.suvkam") },
        { value: "sawa", label: t("Options.subCaste.sawa") },
        { value: "sumian", label: t("Options.subCaste.sumian") },
        { value: "suwam", label: t("Options.subCaste.suwam") },
        { value: "singana", label: t("Options.subCaste.singana") },
        { value: "shabd", label: t("Options.subCaste.shabd") },
        { value: "utam", label: t("Options.subCaste.utam") },
        { value: "uttam", label: t("Options.subCaste.uttam") },
        { value: "wakrecha", label: t("Options.subCaste.wakrecha") },
       
    ],
        
    qualificationOptions : [
      { value: "none", label: t("Options.qualification.none") },
        { value: "secondary", label: t("Options.qualification.secondary") },
        { value: "sr_sec", label: t("Options.qualification.sr_sec") },
        { value: "diploma", label: t("Options.qualification.diploma") },
        { value: "other_professional", label: t("Options.qualification.other_professional") },
        { value: "graduation", label: t("Options.qualification.graduation") },
        { value: "pg", label: t("Options.qualification.pg") },
        { value: "phd", label: t("Options.qualification.phd") },
        
        
    ],
     occupationOptions : [
        { value: "doctor", label: t("Options.occupation.doctor") },
        { value: "engineer", label: t("Options.occupation.engineer") },
        { value: "teacher", label: t("Options.occupation.teacher") },
        { value: "self_employed", label: t("Options.occupation.self_employed") },
        { value: "govt_service", label: t("Options.occupation.govt_service") },
        { value: "pvt_service", label: t("Options.occupation.pvt_service") },
        { value: "labour", label: t("Options.occupation.labour") },
        { value: "student", label: t("Options.occupation.student") },
        { value: "none", label: t("Options.occupation.none") }
    ],
    
     stateOptions : [
        { value: "rajasthan", label: t("Options.location.state.rajasthan") },
    ],
    
    cities: [
  { value: "ajmer", label: t("Options.location.city.ajmer") },
  { value: "alwar", label: t("Options.location.city.alwar") },
  { value: "banswara", label: t("Options.location.city.banswara") },
  { value: "baran", label: t("Options.location.city.baran") },
  { value: "barmer", label: t("Options.location.city.barmer") },
  { value: "bharatpur", label: t("Options.location.city.bharatpur") },
  { value: "bhilwara", label: t("Options.location.city.bhilwara") },
  { value: "bikaner", label: t("Options.location.city.bikaner") },
  { value: "bundi", label: t("Options.location.city.bundi") },
  { value: "chittorgarh", label: t("Options.location.city.chittorgarh") },
  { value: "churu", label: t("Options.location.city.churu") },
  { value: "dausa", label: t("Options.location.city.dausa") },
  { value: "dholpur", label: t("Options.location.city.dholpur") },
  { value: "shri_dungargarh", label: t("Options.location.city.shri_dungargarh") },
  { value: "shri_ganganagar", label: t("Options.location.city.shri_ganganagar") },
  { value: "hanumangarh", label: t("Options.location.city.hanumangarh") },
  { value: "jaipur", label: t("Options.location.city.jaipur") },
  { value: "jaisalmer", label: t("Options.location.city.jaisalmer") },
  { value: "jalore", label: t("Options.location.city.jalore") },
  { value: "jhalawar", label: t("Options.location.city.jhalawar") },
  { value: "jhunjhunu", label: t("Options.location.city.jhunjhunu") },
  { value: "jodhpur", label: t("Options.location.city.jodhpur") },
  { value: "karauli", label: t("Options.location.city.karauli") },
  { value: "kota", label: t("Options.location.city.kota") },
  { value: "nagaur", label: t("Options.location.city.nagaur") },
  { value: "pali", label: t("Options.location.city.pali") },
  { value: "pratapgarh", label: t("Options.location.city.pratapgarh") },
  { value: "rajsamand", label: t("Options.location.city.rajsamand") },
  { value: "sawai_madhopur", label: t("Options.location.city.sawai_madhopur") },
  { value: "sikar", label: t("Options.location.city.sikar") },
  { value: "sirohi", label: t("Options.location.city.sirohi") },
  { value: "tonk", label: t("Options.location.city.tonk") },
  { value: "udaipur", label: t("Options.location.city.udaipur") }
]

  });
  